Repository olbo98/cv-pipeline, pull requests merged in 2022-04, with the labels that each got.

#25 Train loop
  .gitignore
  __pycache__/models.cpython-37.pyc
  __pycache__/utils.cpython-37.pyc
  main.py
  models.py
  module.py
  pool.py
  utils.py
  view.py
Labels: bug, feature

#27 Add script that turns the labels in woodscape to the correct format
  preprocess_woodspace.py
Labels: bug

#29 Strong annotations classes
  __pycache__/models.cpython-37.pyc
  __pycache__/utils.cpython-37.pyc
  main.py
  module.py
  view.py
Labels: feature

#32 Change to woodscape dataset and fix ui bugs
  .gitignore
  main.py
  module.py
  view.py
Labels: bug, feature

#35 Converting to tflite format and applied quantization
  .gitignore
  main.py
  module.py
Labels: feature

#37 Save labels
  main.py
  module.py
  pool.py
  tests/module_test.py
Labels: bug, feature

#39 fix bug when you dont label an image
  .gitignore
  module.py
Labels: bug

#40 Implement mAP
  module.py
  test_mAP.py
Labels: feature

#41 Save map
  main.py
  module.py
  test_mAP.py
  view.py
Labels: bug

#43 mAP for quantized models
  main.py
  module.py
Labels: feature
