Repository olbo98/cv-pipeline, pull requests merged in 2022-03, with the labels that each got.

#3 Pseudo labeling
  __pycache__/adaptive_supervision.cpython-39.pyc
  adaptive_supervision.py
  adaptive_supervision_test.py
Labels: feature

#9 Active sampling
  adaptive_supervision.py
Labels: feature

#10 Soft switch
  adaptive_supervision.py
Labels: feature

#11 Implement query strong annotations and query weak annotations
  __pycache__/adaptive_supervision.cpython-37.pyc
  __pycache__/controller.cpython-37.pyc
  __pycache__/interface.cpython-37.pyc
  __pycache__/model.cpython-37.pyc
  __pycache__/view.cpython-37.pyc
  adaptive_supervision.py
  controller.py
  interface.py
  main.py
  model.py
  view.py
Labels: feature

#13 Strong annotations
  __pycache__/controller.cpython-37.pyc
  __pycache__/model.cpython-37.pyc
  __pycache__/view.cpython-37.pyc
  controller.py
  main.py
  model.py
  view.py
Labels: bug, feature

#17 Fix pools
  model.py
  pool.py
Labels: bug, feature

#18 Add comments for the functions
  .gitignore
  controller.py
  model.py
  view.py
Labels: documentation

#21 Unittests for module.py
  .gitignore
  __pycache__/adaptive_supervision.cpython-37.pyc
  __pycache__/adaptive_supervision.cpython-39.pyc
  __pycache__/interface.cpython-37.pyc
  __pycache__/models.cpython-37.pyc
  __pycache__/utils.cpython-37.pyc
  girl.png
  gitignore.txt
  main.py
  model.py
  model_test.py
Labels: unit tests

#24 Modify program flow
  main.py
  module.py
  view.py
Labels: bug, feature
